import Dispatcher from '../dispatcher/AppDispatcher';

/**
 * `Actions` are generated by `Views` and processed by the `Dispacher` according to the
 * Flux application architecture.
 *
 */
var Actions = {

  TYPES: {
    SET: 'SET',
    ADD: 'ADD',
  },

  set: function(val) {
    Dispatcher.handleViewAction({
      type: Actions.TYPES.SET,
      value: val
    });
  },

  add: function(n) {
    Dispatcher.handleViewAction({
      type: Actions.TYPES.ADD,
      n: n
    });
  }
};

/**
 * Expose `Actions`
 */

export default Actions;